openapi: "3.0.0"
info:
    version: "v1"
    title: "Restaurant API"
    description: An API description
servers:
    - url: "https://3e612ca9-71ed-4302-9e59-efd39149a39c.mock.pstmn.io"
paths:
    /restaurant:
        get:
            summary: "List of Restaurans"
            operationId: listRestaurants
            tags:
                - Restaurants
            responses:
                "200":
                    description: "List of Restaurants"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurants"
                "500":
                    description: "Errors"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurants"
        post:
            summary: "Add a Restaurant"
            operationId: addRestaurant
            requestBody:
                required: true
                description: The restaurant to add.
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/Restaurant"                
            tags:
                - Restaurants
            responses:
                "201":
                    description: "Add a restaurant"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurant"
                "500":
                    description: "Errors"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurant"
    /restaurant/{id}:
        get:
            summary: "Single of Restaurans"
            operationId: getRestaurants
            parameters:
                - name: id
                  in: path
                  description: The unique id.
                  required: true
                  schema:
                      type: string
            tags:
                - Restaurants
            responses:
                "200":
                    description: "List of Restaurants"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurants"
                "500":
                    description: "Errors"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurants"
        put:
            summary: "Update a Restaurant"
            operationId: updateRestaurant
            parameters:
                - name: id
                  in: path
                  description: The unique id.
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                description: Update Restaurant.
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/Restaurant"                
            tags:
                - Restaurants
            responses:
                "204":
                    description: "Add a restaurant"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurant"
                "500":
                    description: "Errors"
        put:
            summary: "Updte a Restaurant"
            operationId: updateRestaurant
            parameters:
                - name: id
                  in: path
                  description: The unique id.
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                description: Update Restaurant.
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/Restaurant"                
            tags:
                - Restaurants
            responses:
                "204":
                    description: "Add a restaurant"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurant"
                "500":
                    description: "Errors"
components:
    schemas:
        Restaurants:
            type: array
            items:
                $ref: "#/components/schemas/Restaurant"
        Restaurant:
            type: object
            required:
                - id
                - name
                - cuisine
            properties:
                id:
                    type: string
                    description: Unique identifier for the restaurant.
                name:
                    type: string
                    description: The name of the restaurant.
                cuisine:
                    type: string
                    description: The cuisine being offer.
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKey: []