openapi: "3.0.0"
info:
    version: "v1"
    title: "Restaurant API"
    description: An API description
servers:
    - url: "https://3e612ca9-71ed-4302-9e59-efd39149a39c.mock.pstmn.io"
paths:
    /restaurant:
        get:
            summary: "List of Restaurans"
            operationId: listRestaurants
            tags:
                - Restaurants
            responses:
                "200":
                    description: "List of Restaurants"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurants"
                "500":
                    description: "Errors"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurants"

        post:
            summary: "Add a Restaurant"
            operationId: addRestaurant
            tags:
                - Restaurants
            responses:
                "201":
                    description: "Add a restaurant"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurant"
                "500":
                    description: "Errors"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Restaurant"

components:
    schemas:
        Restaurants:
            type: array
            items:
                $ref: "#/components/schemas/Restaurant"
        Restaurant:
            type: object
            required:
                - id
                - name
                - cuisine
            properties:
                id:
                    type: string
                    description: Unique identifier for the restaurant.
                name:
                    type: string
                    description: The name of the restaurant.
                cuisine:
                    type: string
                    description: The cuisine being offer.
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKey: []
